apiVersion: apps/v1
kind: Deployment
metadata:
  name: ruby-web
  labels:
    app: ruby-web
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ruby-web
  template:
    metadata:
      name: ruby-web
      labels:
        app: ruby-web
    spec:
      containers:
        - name: ruby-web
          image: vinicaracho/ruby_web_image:latest
          imagePullPolicy: IfNotPresent
          ports:
            - name: ruby-web
              containerPort: 3000
              protocol: TCP
          env:
            - name: DATABASE_HOST
              value: database
            - name: DATABASE_PORT
              value: "5432"
            - name: DATABASE_USER
              value: postgres
            - name: DATABASE_PASSWORD
              value: postgres
            - name: DATABASE_NAME
              value: deputy-database
          command: ["/bin/sh", "-c"]
          args:
            - rm -f /app/tmp/pids/server.pid && bin/rails s -b 0.0.0.0 -p 3000
      restartPolicy: Always
