apiVersion: v1
kind: Service
metadata:
  name: ruby-web
spec:
  selector:
    app: ruby-web
  ports:
    - protocol: TCP
      port: 3000        # Porta exposta no cluster
      targetPort: 3000  # Porta do container
  type: LoadBalancer
  