apiVersion: v1
kind: Pod
metadata:
  name: database
  labels:
    app: database
spec:
  containers:
    - name: etl-postgres
      image: postgres:15
      imagePullPolicy: IfNotPresent
      ports:
        - containerPort: 5432
          protocol: TCP
      env:
        - name: POSTGRES_USER
          value: postgres
        - name: POSTGRES_PASSWORD
          value: postgres
        - name: POSTGRES_DB
          value: deputy-database
      volumeMounts:
        - name: postgres-storage
          mountPath: /var/lib/postgresql/data
  volumes:
    - name: postgres-storage
      emptyDir: { }
  restartPolicy: Always
